// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://divhnbaqpfmoxfuvyrsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpdmhuYmFxcGZtb3hmdXZ5cnNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MDUxMDAsImV4cCI6MjA3MzA4MTEwMH0.BUwBLh9EQ26YqpjF8JdOlzgDNStNQbKqVAYMXoniM08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});